[program:laravel-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/mondomaine.com/artisan reverb:start --host=0.0.0.0 --port=8080 --hostname=mondomaine.com
directory=/var/www/mondomaine.com
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=LARAVEL_ENV="production"
stopsignal=QUIT
stopwaitsecs=20