<?php

use App\Enums\UserRole;

return [
    UserRole::SUPER_ADMIN()->value => [
        // Has all permissions through Gate::before implementation
    ],

    UserRole::ADMIN()->value => [
        'users.view',
        'users.create',
        'users.edit',
        'users.delete',
        'roles.view',
        'roles.create',
        'roles.edit',
        'roles.assign_permissions',
        'distribution_centers.view',
        'distribution_centers.create',
        'distribution_centers.edit',
        'distribution_centers.delete',
        'orders.view',
        'orders.create',
        'orders.edit',
        'orders.delete',
        'orders.assign',
        'deliveries.view',
        'deliveries.create',
        'deliveries.edit',
        'deliveries.delete',
        'deliveries.assign',
        'products.view',
        'products.create',
        'products.edit',
        'products.delete',
        'bottles.track',
        'bottle_types.view',
        'bottle_types.create',
        'bottle_types.edit',
        'bottle_types.delete',
        'accessories.view',
        'accessories.create',
        'accessories.edit',
        'accessories.delete',
        'accessory_types.view',
        'accessory_types.create',
        'accessory_types.edit',
        'accessory_types.delete',
        'suppliers.view',
        'suppliers.create',
        'suppliers.edit',
        'suppliers.delete',
        'supplier_deliveries.view',
        'supplier_deliveries.create',
        'supplier_deliveries.edit',
        'supplier_deliveries.delete',
        'customers.view',
        'customers.create',
        'customers.edit',
        'customers.delete',
        'reports.manage',
        'gas.manage',
        'comments.view',
        'comments.moderate',
    ],

    UserRole::MANAGER()->value => [
        'users.view',
        'users.create',
        'users.edit',
        'distribution_centers.view',
        'distribution_centers.create',
        'distribution_centers.edit',
        'orders.view',
        'orders.create',
        'orders.edit',
        'orders.assign',
        'deliveries.view',
        'deliveries.create',
        'deliveries.edit',
        'deliveries.assign',
        'products.view',
        'products.create',
        'products.edit',
        'bottles.track',
        'customers.view',
        'customers.create',
        'customers.edit',
        'reports.manage',
    ],

    UserRole::ACCOUNTANT()->value => [
        'orders.view',
        'deliveries.view',
        'reports.manage',
        'payments.view',
        'payments.edit',
        'customers.view',
        'comments.view',
    ],

    UserRole::GAS_MANAGER()->value => [
        'gas.manage',
        'products.view',
        'products.create',
        'products.edit',
        'bottles.track',
        'bottle_types.view',
        'bottle_types.edit',
        'suppliers.view',
        'supplier_deliveries.view',
        'supplier_deliveries.create',
        'supplier_deliveries.edit',
        'reports.manage',
    ],

    UserRole::CENTER_MANAGER()->value => [
        'distribution_center.manage_own',
        'distribution_center.assign_deliverers',
        'users.view',
        'orders.view',
        'orders.edit',
        'orders.assign',
        'deliveries.view',
        'deliveries.create',
        'deliveries.edit',
        'deliveries.assign',
        'products.view',
        'products.edit',
        'bottles.track',
        'bottles.assign',
        'accessories.view',
        'accessories.edit',
        'supplier_deliveries.view',
        'supplier_deliveries.create',
        'supplier_deliveries.edit',
        'reports.manage',
        'customers.view',
    ],

    UserRole::DELIVERY_PERSON()->value => [
        'deliveries.view_own',
        'deliveries.edit_own',
        'products.view',
        'bottles.scan',
        'bottles.track',
        'orders.view_assigned',
        'mobile.access',
        'delivery.track_location',
    ],

    UserRole::CUSTOMER()->value => [
        'orders.view_own',
        'orders.create_own',
        'deliveries.track_own',
        'profile.edit',
        'history.view_own',
    ],
];
